version: '3.8'
services:
    userservice:
        build: ./userservice
        ports:
            - "3000:3000"
        environment:
            - MONGO_URI=mongodb://mongodb/userservice
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
volumes:
    mongodb_data:
