version: '3.8'
services:
    userservice:
        build: ./userservice
        ports:
            - "3000:3000"
        environment:
            - MONGO_URI=mongodb://mongodb/userservice
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        depends_on:
            - mongodb
    taskservice:
        build: ./taskService
        ports:
            - "3001:3001"
        environment:
            - MONGO_URI=mongodb://mongodb/taskservice
            - RABBITMQ_URL=amqp://rabbitmq:5672
            - QUEUE_NAME=task_queue
        depends_on:
            - mongodb
            - rabbitmq
volumes:
    mongodb_data:
